cd ../AccelerometerPlay/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../ApiDemos/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../BackupRestore/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../BasicGLSurfaceView/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../ContactManager/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../CubeLiveWallpaper/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../FileBrowser/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../GestureBuilder/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../HelloActivity/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../HelloViews/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../Home/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../JetBoy/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../LunarLander/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../MapsDemo/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../MarketLicensing/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../MultiResolution/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../NFCDemo/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../NotePad/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../PhoneDialer/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../SearchableDictionary/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../Snake/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../Support4Demos/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../TicTacToeLib/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../TicTacToeMain/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
cd ../Wiktionary/ ; ln -s ../configs/ant/ant-windows.properties ant.properties; ln -s ../configs/ant/build-scala.xml .
